### ISSUE TITLE
Create and implement algorithm for solving the task

### ISSUE THREAD

**Issue by Phyteon** [Phyteon/konserwatorium#2]
Please develop an algorithm for solving the task. Any sketches/scratches should be documented under this issue (metacode, diagrams, etc.)

**Comment by Phyteon** [comment]
Algorithm sketch:
- pick one good cell from starting edge (at random),
- from that cell, go to the good adjacent cell (if it has any)
- repeat the process until no good cell has not visited neighbours

**Comment by Phyteon** [comment]
![image](https://user-images.githubusercontent.com/43323207/169713779-be3da56d-5d6c-46e8-a2a6-ef75914e41a7.png)

**Comment by Phyteon** [comment]
If there are multiple entry points but they ultimately lead to the same route, we can skip them by checking if the entry point was ever visited.

**Comment by KrzSko20** [comment]
![image](https://user-images.githubusercontent.com/48729635/169864074-8041df31-4c27-4f86-ada1-03b5541f288d.png)

**Comment by Phyteon** [comment]
METACODE:
```
string find_route(Node &node) {
   string route = str(node);
   for pointee in node.negihbours if not pointee.visited {
      route += find_route(pointee);
      pointee.visited = true;
   }
}
```

**Comment by Phyteon** [comment]
Additional remarks:
- data will be provided as a linked list
- for optimization, function can be called only on not visited nodes
